slam_toolbox:
  ros__parameters:
    # 動作モード："mapping"（オンラインで地図作成）または "localization"（既存地図に自己位置推定）
    mode: "mapping"

    # 地図保存時のファイル名（保存機能を利用する場合）
    map_file_name: "map"

    # シミュレーション時間を利用する場合はtrueに
    use_sim_time: false

    # 地図の解像度 [m/cell]
    resolution: 0.05

    # センサーデータの最大有効距離
    max_laser_range: 30.0

    # LiDARのスキャンデータのトピック名
    scan_topic: "/scan"

    # 各種フレームの設定（環境に合わせて変更してください）
    base_frame: "base_link"
    odom_frame: "odom"
    map_frame: "map"

    # その他パラメータは必要に応じて追加・調整してください
